### ISSUE TITLE
Branches for new releases

### ISSUE THREAD

**Issue by rgomez90** [PromoFaux/Matterhook.NET.MatterhookClient#13]
@PromoFaux I think we should use branches for our releases,i.e. we should create a branch name `v1.4` and a branch named `v1.5`. 

This way we have a cleaner organisation. 

I would delete my PR from the master and merged it in the branch `v1.4`, but since it is protected only you can do this (afaik).

**Comment by PromoFaux** [comment]
Just pulled some #admincrimes (reset master to commit before your changes were merged in then force pushed 😉)

Either that or a single `development` branch

**Comment by rgomez90** [comment]
Great, that was quick. Regarding the branches, you choose.

I think a good strategy is:

* master branch
  * vx.x branch
    * featue/description
    * bugfix/description

So we have a branch for each new feature/ bugfix which will be merged into the specific version we worked at it. When the version is ready for release, we merge it to master (and some CI does the job of generating nuget etc etc)..

As said I am not a Git pro, since I used to work as solo dev and I still have a lot to learn.

The main idea comes from [this Microsoft's article ](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-branching-guidance?view=vsts), which in my honest and not so competent opinion looks good for simple projects.

**Comment by PromoFaux** [comment]
Something that has worked well on other projects I've worked on is having a `master` and a `development` branch.

All development work goes into (you guessed it!) `development`, and when it's ready to release, `development` is merged into `master` and then a tag is created (See the [releases](https://github.com/PromoFaux/Matterhook.NET.MatterhookClient/releases) page), which is how we do things over on https://github.com/pi-hole/pi-hole and it works!

I've always found this really helpful: 

![image](https://user-images.githubusercontent.com/1998970/47376736-4fd7c700-d6eb-11e8-9f6b-f1051477cf94.png)

Though generally skip the bit between `dev` -> `master`

Because I was only really working on my own before I didn't really bother with anything other than `master`

**Comment by PromoFaux** [comment]
OK, I've set up a `development` branch, and created a WIP PR for now to show the direction of things.

**Comment by rgomez90** [comment]
Nice! Then this is the way to go. You can close this issue I think. 😄
