### ISSUE TITLE
How can I get the "post id" after posting a message

### ISSUE THREAD

**Issue by etcy** [PromoFaux/Matterhook.NET.MatterhookClient#29]
I want to:
- Create a post, "Hello this is a post"
- And also add a reaction to it, eg ":thumbs-up:"

How can I achieve this? Any ideas?

**Comment by PromoFaux** [comment]
Hi there, as far as I'm aware you cannot do this via webhooks. Although it has been a long time since I read [the documentation.](https://developers.mattermost.com/integrate/other-integrations/incoming-webhooks/)

The main purpose of this project is to post simple (one way) messages to a Mattermost server, I didn't ever build any 2 way interaction to it - although @rgomez90 later added some more advanced message types including [interactive messages](https://developers.mattermost.com/integrate/admin-guide/admin-interactive-messages/), but I've never actually used them. He may have some ideas.

**Comment by PromoFaux** [comment]
@etcy  you're probably best off looking at [plugins](https://developers.mattermost.com/integrate/plugins/) for anything more fancy than a simple payload!

**Comment by rgomez90** [comment]
@etcy you can't do that with webhooks.

For this you should use the [Mattermost API](https://api.mattermost.com/#operation/CreatePost). 

If I remember correctly, there you get the post id in the response. Then you can use this id to add a reaction like you want, see [Reactions](https://api.mattermost.com/#operation/SaveReaction)

**Comment by etcy** [comment]
@rgomez90 
Thank you for the advice. I will check out the links and use your idea to try.
